name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Swap README for Hugging Face
        run: |
          cp HF_README.md README.md
          git config user.email "ci@github.com"
          git config user.name "CI Bot"
          git add README.md
          git commit -m "Swap README for HF Spaces" --allow-empty

      - name: Configure git credentials for Hugging Face
        run: |
          git config --global credential.helper store
          echo "https://mayukh30:${{ secrets.PREDICTLOAN }}@huggingface.co" > ~/.git-credentials

      - name: Push to Hugging Face
        run: git push --force https://huggingface.co/spaces/mayukh30/loan-prediction main
